#!/bin/bash -eu

if docker ps -a | grep -q fez; then
  docker stop fez
  docker rm fez
fi

if [ "${1:-}" = '-s' ]; then
  docker run -ti --name fez goyishekop/dockerbook
else
  docker run -dp 127.0.0.1:2222:22 --name fez goyishekop/dockerbook /usr/sbin/sshd -D
  sleep 1
  ssh localhost -p 2222
fi
